# Generated by Django 5.2.3 on 2025-06-19 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta_nom', models.CharField(max_length=100)),
                ('tipo_planta', models.CharField(blank=True, max_length=50)),
                ('cuidados', models.TextField(blank=True)),
                ('foto_url', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_noti', models.CharField(choices=[('riego', 'Riego'), ('poda', 'Poda'), ('fertilización', 'Fertilización'), ('limpieza', 'Limpieza'), ('luz', 'Luz'), ('temperatura', 'Temperatura')], max_length=20)),
                ('fecha_envio', models.DateTimeField()),
                ('enviado', models.BooleanField(default=False)),
                ('mensaje', models.TextField(blank=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huerto_app.planta')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('riego', 'Riego'), ('poda', 'Poda'), ('fertilización', 'Fertilización'), ('limpieza', 'Limpieza'), ('luz', 'Luz'), ('temperatura', 'Temperatura')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huerto_app.planta')),
            ],
        ),
        migrations.CreateModel(
            name='CuidadoProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cuidado', models.CharField(choices=[('riego', 'Riego'), ('poda', 'Poda'), ('fertilización', 'Fertilización'), ('limpieza', 'Limpieza'), ('luz', 'Luz'), ('temperatura', 'Temperatura')], max_length=20)),
                ('frecuen_dias', models.IntegerField()),
                ('prox_fecha', models.DateTimeField()),
                ('detalles', models.TextField(blank=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huerto_app.planta')),
            ],
        ),
        migrations.AddField(
            model_name='planta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huerto_app.usuario'),
        ),
    ]
