# Generated by Django 5.2.3 on 2025-07-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huerto_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('riego', 'Riego'), ('poda', 'Poda'), ('fertilización', 'Fertilización'), ('limpieza', 'Limpieza'), ('luz', 'Luz'), ('temperatura', 'Temperatura')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'historial',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cuidadoprogramado',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='planta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='HistorialAccion',
        ),
    ]
